// Auto-generated by scripts/build-content-index.js
(function(){
  window.CONTENT_INDEX = {
    projects: [
  {
    "title": "Detecting Financial Statement Fraud with ML",
    "slug": "detect-fs-fraud",
    "date": "2020-05-01",
    "datePretty": "May 1, 2020",
    "description": "How machine learning can detect accounting fraud",
    "image": "assets/fs-ml.jpg",
    "alt": "An article on detecting financial statrment fraud with machine learning ",
    "externalLink": "https://medium.com/data-science/detecting-firms-with-intentional-misstatements-using-machine-learning-a943191f88cf",
    "tags": [
      "Featured",
      "Fraud detection",
      "Machine learning"
    ]
  },
  {
    "title": "Visualizing Singapore Government Spending test page",
    "slug": "visualise-spending-test",
    "date": "2019-01-01",
    "datePretty": "Jan 1, 2019",
    "description": "Insights into the spending pattern of each Ministry and Agency of Singapore Government",
    "image": "assets/Geviz_project_cover.png",
    "alt": "Singapore government spending dashboard showing budget allocation across ministries with interactive charts",
    "imageLink": "https://is428-ay1819-geviz.shinyapps.io/Group7_GeViz/",
    "tags": [
      "Dashboard",
      "R Shiny",
      "Working in progress"
    ],
    "gallery": [
      {
        "src": "assets/geviz/treemap.png",
        "title": "An Overview of Agency Spending within Each Ministry",
        "alt": "Overview",
        "caption": "Treemap chart is used here to provide a birds-eye view of each each ministry's spending breakdown by agency and category. The size of the box represents number of procurement contracts of each procurement category while the colour intensity represents the total amount of good and services procured."
      },
      {
        "src": "assets/geviz/network.jpeg",
        "title": "Relationships Between Agencies and Suppliers",
        "alt": "Breakdown",
        "caption": "To best represent the interlinked relationship beteewen suppliers and agencies under a selected ministry, network diagram was used to shows the common suppliers between agencies. The triangle icon represents agencies while the circle icon represents suppliers."
      },
      {
        "src": "assets/geviz/sangkey.jpeg",
        "title": "Main Suppliers of an Agency by Spending Category",
        "alt": "Sankey",
        "caption": "This sankey diagram was created with R's NetworkD3 library, the chart shows the cash flow between a selected agency and its suppliers for a selected procurement category. The thickness of the path represents the total dollar amount of goods and services procured from a particular supplier."
      },
      {
        "src": "assets/geviz/wordcloud.jpeg",
        "title": "A Glimpse into Goods and Services Procured",
        "alt": "Word cloud",
        "caption": "This word cloud was created with R's Wordcloud2 library, it shows the top goods and services procured by a selected agency and a selected category. The size of the word within the word cloud corresponds to the frequency of the word in the procurement descriptions."
      }
    ]
  },
  {
    "title": "Visualizing Singapore Government Spending",
    "slug": "visualise-spending",
    "date": "2019-01-01",
    "datePretty": "Jan 1, 2019",
    "description": "Insights into the spending pattern of each Ministry and Agency of Singapore Government",
    "image": "assets/Geviz_project_cover.png",
    "alt": "Singapore government spending dashboard showing budget allocation across ministries with interactive charts",
    "imageLink": "https://is428-ay1819-geviz.shinyapps.io/Group7_GeViz/",
    "externalLink": "https://wiki.smu.edu.sg/18191is428g1/GeViz",
    "tags": [
      "Featured",
      "Dashboard",
      "R Shiny",
      "Working in progress"
    ],
    "gallery": [
      {
        "src": "assets/geviz/treemap.png",
        "title": "An Overview of Agency Spending within Each Ministry",
        "alt": "Overview",
        "caption": "Treemap chart is used here to provide a birds-eye view of each each ministry's spending breakdown by agency and category. The size of the box represents number of procurement contracts of each procurement category while the colour intensity represents the total amount of good and services procured."
      },
      {
        "src": "assets/geviz/network.jpeg",
        "title": "Relationships Between Agencies and Suppliers",
        "alt": "Breakdown",
        "caption": "To best represent the interlinked relationship beteewen suppliers and agencies under a selected ministry, network diagram was used to shows the common suppliers between agencies. The triangle icon represents agencies while the circle icon represents suppliers."
      },
      {
        "src": "assets/geviz/sangkey.jpeg",
        "title": "Main Suppliers of an Agency by Spending Category",
        "alt": "Sankey",
        "caption": "This sankey diagram was created with R's NetworkD3 library, the chart shows the cash flow between a selected agency and its suppliers for a selected procurement category. The thickness of the path represents the total dollar amount of goods and services procured from a particular supplier."
      },
      {
        "src": "assets/geviz/wordcloud.jpeg",
        "title": "A Glimpse into Goods and Services Procured",
        "alt": "Word cloud",
        "caption": "This word cloud was created with R's Wordcloud2 library, it shows the top goods and services procured by a selected agency and a selected category. The size of the word within the word cloud corresponds to the frequency of the word in the procurement descriptions."
      }
    ]
  }
],
    posts: [
  {
    "title": "Notes on prompt engineering",
    "slug": "prompt-engineering",
    "date": "2025-09-08",
    "datePretty": "Sep 8, 2025",
    "excerpt": " My cheatsheet on prompt engineering from Google's whitepaper",
    "tags": [
      "Coming soon"
    ]
  }
]
  };
})();
